export const CARD_BG = [
  { bgcolor: 'linear-gradient(135deg, #1a0a2e 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #0f1535 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #1a0d38 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #120a30 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #0c1230 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #150a3a 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #0e1835 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #180a32 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #0c1530 0%, #0e0e19 100%)' },
  { bgcolor: 'linear-gradient(135deg, #140a38 0%, #0e0e19 100%)' },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no two prep sessions are the same.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized and effective.",
  },
  {
    id: "04",
    title: "Understand the Why Behind Answers",
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Track Your Progress",
    description:
      "Visualize your performance over time. Identify your strengths and weaknesses to focus your efforts where they matter most.",
  },
];
